apiVersion: v1
kind: Service
metadata:
  name: mysql-metrics
  namespace: mysql-ha
  labels: 
    app: mysql-metrics
    jobLabel: mysql
    release: prometheus-operator
spec:
  type: ClusterIP
  ports:
  - name: metrics
    port: 9104
    targetPort: 9104
    protocol: TCP
  selector:
    app: mysql
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-headless
  namespace: mysql-ha
  labels: 
    app: mysql
spec:
  ports:
  - name: tcp
    port: 3306
    targetPort: 3306
    protocol: TCP
  clusterIP: None
  selector:
    app: mysql
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-read
  namespace: mysql-ha
  labels: 
    app: mysql
spec:
  ports:
  - name: tcp
    port: 3306
    targetPort: 3306
    protocol: TCP
  selector:
    app: mysql
